-- backend/migrations/002_add_user_activity_tracking.sql
-- Up Migration

ALTER TABLE users ADD COLUMN IF NOT EXISTS date_joined TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS opened_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS closed_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active TIMESTAMP WITH TIME ZONE;

-- Down Migration
-- ALTER TABLE users DROP COLUMN IF EXISTS date_joined;
-- ALTER TABLE users DROP COLUMN IF EXISTS opened_time;
-- ALTER TABLE users DROP COLUMN IF EXISTS closed_time;
-- ALTER TABLE users DROP COLUMN IF EXISTS last_active;
